version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "sentipy"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-cr1yqh796kuj"
s3_prefix = "sentipy"
region = "ap-southeast-1"
capabilities = "CAPABILITY_IAM"
image_repositories = ["Sentipy=833148443366.dkr.ecr.ap-southeast-1.amazonaws.com/sentipy76797fc0/sentipyb92da269repo"]
