version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "revalidaAPP"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-cr1yqh796kuj"
s3_prefix = "revalidaAPP"
region = "ap-southeast-1"
capabilities = "CAPABILITY_IAM"
image_repositories = ["Revalida=833148443366.dkr.ecr.ap-southeast-1.amazonaws.com/revalidaappc4708d64/revalidaa96945e8repo"]
